logging:
  file: "commands.log"
  format: "[{date}] {prefix}{player}: /{command}"
  date-format: "dd/MM/yyyy HH:mm:ss"

log-all: true # логгировать всё комманды?

need-permission: # например для логгирования только админов, модеров и тп
  - "default" # всё, логгировать всех и вся

excluded-commands: # исключение (только если включён 'log-all')
  - ""

enabled-commands: # изменить
  - 'op'
  - 'deop'
  - 'gamemode'
  - 'give'
  - 'tp'
  - 'ban'
  - 'ban-ip'
  - 'pardon'
  - 'pardon-ip'
  - 'kick'
  - 'kill'
  - 'stop'
  - 'restart'