logging:
  file: "commands.log"
  format: "[{date}] {prefix} {player}: /{command}"
  date-format: "dd/MM/yyyy HH:mm:ss"

log-all: true # логгировать всё? (все команды)

excluded-commands: # исключение (только если включён 'log-all')
  - ""

enabled-commands: # изменить
  - 'op'
  - 'deop'
  - 'gamemode'
  - 'give'
  - 'tp'
  - 'ban'
  - 'ban-ip'
  - 'pardon'
  - 'pardon-ip'
  - 'kick'
  - 'kill'
  - 'stop'
  - 'restart'